apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: learner-report-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: yashbbhatt/container_orch_frontend:latest
        env:
        - name: REACT_APP_BACKEND_URL
          valueFrom:
            configMapKeyRef:
              name: frontend-config
              key: REACT_APP_BACKEND_URL
        resources:
          limits:
            memory: "2048Mi"
            cpu: "2000m"
        ports:
        - containerPort: 3000