apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  namespace: db
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /Users/yashbhatt/Desktop/Yash/Devops/HeroVired/Kubernetes/Container-Orchatration-Automation/data
  #persistentVolumeReclaimPolicy: Recycle
  #storageClassName: slow
  # mountOptions:
  #   - hard
  #   - nfsvers=4.1
  # nfs:
  #   path: /tmp
  #   server: 172.17.0.2
