apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  namespace: database
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    #path: /mnt/data
    path: /Users/yashbhatt/Desktop/Yash/Devops/HeroVired/Kubernetes/TravelMemory-K8s/data