apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: db-app
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
