apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: node-backend
spec:
  type: ClusterIP
  selector:
    app: backend-service
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
